#version 460

#extension GL_KHR_shader_subgroup_basic : require
#extension GL_EXT_buffer_reference : require

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

struct CustomCommand {
    uint groupCountX;
    uint groupCountY;
    uint groupCountZ;
    uint workgroupOffset;
};

struct Command {
    uint groupCountX;
    uint groupCountY;
    uint groupCountZ;
};

layout(buffer_reference) buffer CommandBuffer {
    CustomCommand commands[];
};

layout(buffer_reference) buffer iCommandBuffer {
    Command command;
};

layout(push_constant) uniform PushConstants {
    CommandBuffer commands;
    iCommandBuffer iCommand;
} pc;

layout(set = 0, binding = 0) uniform texture2D textures[];
layout(set = 0, binding = 1) uniform writeonly image2D images[];
layout(set = 0, binding = 2) uniform sampler samplers[1];
layout(set = 0, binding = 2) uniform samplerShadow shadowSamplers[1];

shared uint xCount;

void main() {
    uint actualGroupID = gl_WorkGroupID.x;

    uint groupCount = gl_NumWorkGroups.x;
    uint localID = gl_LocalInvocationID.x;
    
    uint groupID = groupCount - 1 - actualGroupID;

    if (subgroupElect()) {
        xCount = 0;
        pc.commands.commands[groupID].workgroupOffset = 0;
    }
    barrier();

    for (uint i = localID;i < groupID;i += 32) {
        atomicAdd(xCount, pc.commands.commands[i].groupCountX);
    }
    barrier();
    
    if (subgroupElect()) {
        pc.commands.commands[groupID].workgroupOffset = xCount;
        atomicAdd(pc.iCommand.command.groupCountX, pc.commands.commands[groupID].groupCountX);
    }
}
