 const vk = @import("vulkan").vulkan; const VkError = @import("vulkanType.zig").VkError;
pub const vulkanType= @import("vulkanType.zig");
 const VkResult = vulkanType.VkResult;
 pub fn VkResultToError(result: VkResult) VkError!void {
return switch(result) {
.VK_ERROR_OUT_OF_HOST_MEMORY => VkError.VK_ERROR_OUT_OF_HOST_MEMORY,
.VK_ERROR_OUT_OF_DEVICE_MEMORY => VkError.VK_ERROR_OUT_OF_DEVICE_MEMORY,
.VK_ERROR_INITIALIZATION_FAILED => VkError.VK_ERROR_INITIALIZATION_FAILED,
.VK_ERROR_DEVICE_LOST => VkError.VK_ERROR_DEVICE_LOST,
.VK_ERROR_MEMORY_MAP_FAILED => VkError.VK_ERROR_MEMORY_MAP_FAILED,
.VK_ERROR_LAYER_NOT_PRESENT => VkError.VK_ERROR_LAYER_NOT_PRESENT,
.VK_ERROR_EXTENSION_NOT_PRESENT => VkError.VK_ERROR_EXTENSION_NOT_PRESENT,
.VK_ERROR_FEATURE_NOT_PRESENT => VkError.VK_ERROR_FEATURE_NOT_PRESENT,
.VK_ERROR_INCOMPATIBLE_DRIVER => VkError.VK_ERROR_INCOMPATIBLE_DRIVER,
.VK_ERROR_TOO_MANY_OBJECTS => VkError.VK_ERROR_TOO_MANY_OBJECTS,
.VK_ERROR_FORMAT_NOT_SUPPORTED => VkError.VK_ERROR_FORMAT_NOT_SUPPORTED,
.VK_ERROR_FRAGMENTED_POOL => VkError.VK_ERROR_FRAGMENTED_POOL,
.VK_ERROR_UNKNOWN => VkError.VK_ERROR_UNKNOWN,
.VK_ERROR_OUT_OF_POOL_MEMORY => VkError.VK_ERROR_OUT_OF_POOL_MEMORY,
.VK_ERROR_INVALID_EXTERNAL_HANDLE => VkError.VK_ERROR_INVALID_EXTERNAL_HANDLE,
.VK_ERROR_FRAGMENTATION => VkError.VK_ERROR_FRAGMENTATION,
.VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS => VkError.VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS,
.VK_ERROR_NOT_PERMITTED => VkError.VK_ERROR_NOT_PERMITTED,
.VK_ERROR_SURFACE_LOST_KHR => VkError.VK_ERROR_SURFACE_LOST_KHR,
.VK_ERROR_NATIVE_WINDOW_IN_USE_KHR => VkError.VK_ERROR_NATIVE_WINDOW_IN_USE_KHR,
.VK_ERROR_OUT_OF_DATE_KHR => VkError.VK_ERROR_OUT_OF_DATE_KHR,
.VK_ERROR_INCOMPATIBLE_DISPLAY_KHR => VkError.VK_ERROR_INCOMPATIBLE_DISPLAY_KHR,
.VK_ERROR_VALIDATION_FAILED_EXT => VkError.VK_ERROR_VALIDATION_FAILED_EXT,
.VK_ERROR_INVALID_SHADER_NV => VkError.VK_ERROR_INVALID_SHADER_NV,
.VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR => VkError.VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR,
.VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR => VkError.VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR,
.VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR => VkError.VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR,
.VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR => VkError.VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR,
.VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR => VkError.VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR,
.VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR => VkError.VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR,
.VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT => VkError.VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT,
.VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT => VkError.VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT,
.VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR => VkError.VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR,
.VK_ERROR_COMPRESSION_EXHAUSTED_EXT => VkError.VK_ERROR_COMPRESSION_EXHAUSTED_EXT,
.VK_ERROR_NOT_ENOUGH_SPACE_KHR => VkError.VK_ERROR_NOT_ENOUGH_SPACE_KHR,
else => {},
};
}
 pub fn checkVkResult(result: vk.VkResult) VkError!void { VkResultToError(@enumFromInt(result)) catch |err| { return err; };  
}
